const { Resend } = require("resend");

function getResend() {
  if (!process.env.RESEND_API_KEY) throw new Error("RESEND_API_KEY is not set");
  return new Resend(process.env.RESEND_API_KEY);
}

function getFrom() {
  const name  = process.env.FROM_NAME  || "Bloomvera Autism";
  const email = process.env.FROM_EMAIL || "noreply@bloomveraautism.com";
  return `${name} <${email}>`;
}

function getYear()  { return new Date().getFullYear(); }
function getTimestamp() {
  return new Date().toLocaleString("en-US", { dateStyle: "full", timeStyle: "short" });
}

// ─────────────────────────────────────────────────────────────────
// SHARED STYLE CONSTANTS (inline for email clients)
// ─────────────────────────────────────────────────────────────────
const GRAD   = "background:linear-gradient(135deg,#FF7A00 0%,#E91E63 100%)";
const FOOTER = `background:#F9FAFB;padding:20px 32px;border-top:1px solid #E5E7EB;`;

// ─────────────────────────────────────────────────────────────────
// 1. CONTACT — ADMIN NOTIFICATION
// ─────────────────────────────────────────────────────────────────
async function sendAdminEmail({ name, email, phone, message }) {
  const resend = getResend();
  const ADMIN  = process.env.ADMIN_EMAIL;
  if (!ADMIN) throw new Error("ADMIN_EMAIL is not set");

  const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>New Contact Inquiry — Bloomvera Autism</title></head>
<body style="margin:0;padding:0;background:#F9FAFB;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#F9FAFB;padding:40px 16px;">
<tr><td align="center">
<table width="100%" cellpadding="0" cellspacing="0" style="max-width:580px;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">

  <!-- HEADER -->
  <tr><td style="${GRAD};padding:28px 32px;">
    <p style="margin:0;font-size:11px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:rgba(255,255,255,0.8);">New Contact Form Inquiry</p>
    <h1 style="margin:6px 0 0;font-size:22px;font-weight:700;color:#fff;">Bloomvera Autism</h1>
  </td></tr>

  <!-- ALERT BANNER -->
  <tr><td style="background:#FFF5EB;border-left:4px solid #FF7A00;padding:14px 32px;">
    <p style="margin:0;font-size:13px;color:#CC6200;font-weight:600;">🔔 A new inquiry was submitted via the Contact form.</p>
  </td></tr>

  <!-- DETAILS -->
  <tr><td style="padding:32px;">
    <h2 style="margin:0 0 20px;font-size:16px;font-weight:700;color:#111827;">Contact Details</h2>
    <table width="100%" cellpadding="0" cellspacing="0">
      <tr><td style="padding:10px 0;border-bottom:1px solid #F3F4F6;">
        <p style="margin:0;font-size:11px;font-weight:700;color:#9CA3AF;text-transform:uppercase;letter-spacing:0.08em;">👤 Full Name</p>
        <p style="margin:4px 0 0;font-size:14px;color:#111827;font-weight:600;">${name}</p>
      </td></tr>
      <tr><td style="padding:10px 0;border-bottom:1px solid #F3F4F6;">
        <p style="margin:0;font-size:11px;font-weight:700;color:#9CA3AF;text-transform:uppercase;letter-spacing:0.08em;">📧 Email</p>
        <p style="margin:4px 0 0;font-size:14px;"><a href="mailto:${email}" style="color:#FF7A00;text-decoration:none;">${email}</a></p>
      </td></tr>
      <tr><td style="padding:10px 0;border-bottom:1px solid #F3F4F6;">
        <p style="margin:0;font-size:11px;font-weight:700;color:#9CA3AF;text-transform:uppercase;letter-spacing:0.08em;">📞 Phone</p>
        <p style="margin:4px 0 0;font-size:14px;color:#111827;">${phone || '<span style="color:#9CA3AF;">Not provided</span>'}</p>
      </td></tr>
      <tr><td style="padding:10px 0;">
        <p style="margin:0;font-size:11px;font-weight:700;color:#9CA3AF;text-transform:uppercase;letter-spacing:0.08em;">🕐 Submitted</p>
        <p style="margin:4px 0 0;font-size:14px;color:#111827;">${getTimestamp()}</p>
      </td></tr>
    </table>

    <!-- MESSAGE -->
    <div style="margin-top:24px;">
      <p style="margin:0 0 10px;font-size:11px;font-weight:700;color:#9CA3AF;text-transform:uppercase;letter-spacing:0.08em;">💬 Message</p>
      <div style="background:#F9FAFB;border:1px solid #E5E7EB;border-radius:10px;padding:16px;">
        <p style="margin:0;font-size:14px;color:#374151;line-height:1.75;white-space:pre-wrap;">${message}</p>
      </div>
    </div>

    <!-- REPLY CTA -->
    <div style="margin-top:28px;text-align:center;">
      <a href="mailto:${email}?subject=Re: Your Bloomvera Inquiry"
        style="display:inline-block;padding:13px 32px;${GRAD};color:#fff;font-size:14px;font-weight:700;text-decoration:none;border-radius:12px;">
        Reply to ${name}
      </a>
    </div>
  </td></tr>

  <!-- FOOTER -->
  <tr><td style="${FOOTER}">
    <p style="margin:0;font-size:11px;color:#9CA3AF;text-align:center;line-height:1.6;">
      Auto-generated by Bloomvera Autism contact form<br/>
      © ${getYear()} Bloomvera Autism · info@bloomveraautism.com
    </p>
  </td></tr>

</table>
</td></tr></table>
</body></html>`;

  const result = await resend.emails.send({
    from: getFrom(), to: ADMIN, reply_to: email,
    subject: `📩 New Contact Inquiry from ${name} — Bloomvera Autism`,
    html,
  });
  if (result.error) throw new Error(result.error.message);
  return result;
}

// ─────────────────────────────────────────────────────────────────
// 2. CONTACT — USER CONFIRMATION
// ─────────────────────────────────────────────────────────────────
async function sendUserConfirmationEmail({ name, email }) {
  const resend  = getResend();
  const siteUrl = process.env.FRONTEND_URL || "https://bloomveraautism.com";

  const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>We received your message — Bloomvera Autism</title></head>
<body style="margin:0;padding:0;background:#F9FAFB;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#F9FAFB;padding:40px 16px;">
<tr><td align="center">
<table width="100%" cellpadding="0" cellspacing="0" style="max-width:580px;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.07);">

  <!-- HEADER -->
  <tr><td style="${GRAD};padding:36px 32px;text-align:center;">
    <p style="margin:0 0 6px;font-size:36px;">🌸</p>
    <h1 style="margin:0;font-size:24px;font-weight:700;color:#fff;">Message Received!</h1>
    <p style="margin:8px 0 0;font-size:14px;color:rgba(255,255,255,0.85);">Thank you for contacting Bloomvera Autism</p>
  </td></tr>

  <!-- BODY -->
  <tr><td style="padding:36px 32px;">
    <p style="margin:0 0 16px;font-size:15px;color:#111827;font-weight:600;">Hi ${name},</p>
    <p style="margin:0 0 16px;font-size:14px;color:#6B7280;line-height:1.75;">
      Thank you for reaching out to us. We've received your message and our team will get back to you within <strong style="color:#111827;">one business day</strong>.
    </p>

    <!-- WHAT HAPPENS NEXT -->
    <div style="background:#FFF5EB;border-radius:12px;padding:20px 24px;margin-bottom:28px;">
      <p style="margin:0 0 16px;font-size:12px;font-weight:700;color:#CC6200;text-transform:uppercase;letter-spacing:0.08em;">What Happens Next</p>
      ${[
        ["#FF7A00","1","Our team reviews your message","Usually within a few hours"],
        ["#FF7A00","2","We reach out personally","By phone or email — your preference"],
        ["#00A651","3","Free consultation","No obligation, just a conversation"],
      ].map(([color, num, title, sub]) => `
      <table cellpadding="0" cellspacing="0" style="margin-bottom:14px;"><tr>
        <td style="vertical-align:top;padding-right:12px;">
          <div style="width:24px;height:24px;background:${color};border-radius:50%;text-align:center;line-height:24px;">
            <span style="font-size:11px;font-weight:700;color:#fff;">${num}</span>
          </div>
        </td>
        <td>
          <p style="margin:0;font-size:13px;font-weight:600;color:#111827;">${title}</p>
          <p style="margin:2px 0 0;font-size:12px;color:#9CA3AF;">${sub}</p>
        </td>
      </tr></table>`).join("")}
    </div>

    <!-- CTA -->
    <div style="text-align:center;margin-bottom:28px;">
      <a href="${siteUrl}/services"
        style="display:inline-block;padding:13px 32px;${GRAD};color:#fff;font-size:14px;font-weight:700;text-decoration:none;border-radius:12px;">
        Explore Our Programs
      </a>
    </div>

    <!-- PHONE -->
    <div style="border-top:1px solid #F3F4F6;padding-top:20px;text-align:center;">
      <p style="margin:0 0 4px;font-size:12px;color:#9CA3AF;">Prefer to talk now? Call us:</p>
      <a href="tel:+17744642639" style="font-size:18px;font-weight:700;color:#FF7A00;text-decoration:none;">+1 774-464-2639</a>
    </div>
  </td></tr>

  <!-- FOOTER -->
  <tr><td style="${FOOTER}">
    <p style="margin:0;font-size:11px;color:#9CA3AF;text-align:center;line-height:1.7;">
      <strong style="color:#374151;">Bloomvera Autism</strong><br/>
      info@bloomveraautism.com &nbsp;·&nbsp; +1 774-464-2639<br/>
      2823 Marietta St, Steilacoom, WA 98388<br/><br/>
      © ${getYear()} Bloomvera Autism. All rights reserved.
    </p>
  </td></tr>

</table>
</td></tr></table>
</body></html>`;

  const result = await resend.emails.send({
    from: getFrom(), to: email,
    subject: "✅ We received your message — Bloomvera Autism",
    html,
  });
  if (result.error) throw new Error(result.error.message);
  return result;
}

// ─────────────────────────────────────────────────────────────────
// 3. CAREER — ADMIN NOTIFICATION (with resume attachment)
// ─────────────────────────────────────────────────────────────────
async function sendCareerAdminEmail({ fullName, email, phone, position, message, resumeFile }) {
  const resend = getResend();
  const ADMIN  = process.env.ADMIN_EMAIL;
  if (!ADMIN) throw new Error("ADMIN_EMAIL is not set");

  const attachments = [];
  if (resumeFile) {
    attachments.push({
      filename: resumeFile.originalname,
      content:  resumeFile.buffer,           // Buffer from multer memoryStorage
    });
  }

  const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>New Career Application — Bloomvera Autism</title></head>
<body style="margin:0;padding:0;background:#F9FAFB;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#F9FAFB;padding:40px 16px;">
<tr><td align="center">
<table width="100%" cellpadding="0" cellspacing="0" style="max-width:580px;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">

  <!-- HEADER -->
  <tr><td style="${GRAD};padding:28px 32px;">
    <p style="margin:0;font-size:11px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:rgba(255,255,255,0.8);">New Job Application</p>
    <h1 style="margin:6px 0 0;font-size:22px;font-weight:700;color:#fff;">Bloomvera Autism — Career</h1>
  </td></tr>

  <!-- ALERT BANNER -->
  <tr><td style="background:#F0FDF4;border-left:4px solid #00A651;padding:14px 32px;">
    <p style="margin:0;font-size:13px;color:#166534;font-weight:600;">💼 A new job application has been submitted.</p>
  </td></tr>

  <!-- APPLICANT DETAILS -->
  <tr><td style="padding:32px;">
    <h2 style="margin:0 0 20px;font-size:16px;font-weight:700;color:#111827;">Applicant Details</h2>
    <table width="100%" cellpadding="0" cellspacing="0">
      <tr><td style="padding:10px 0;border-bottom:1px solid #F3F4F6;">
        <p style="margin:0;font-size:11px;font-weight:700;color:#9CA3AF;text-transform:uppercase;letter-spacing:0.08em;">👤 Full Name</p>
        <p style="margin:4px 0 0;font-size:14px;color:#111827;font-weight:600;">${fullName}</p>
      </td></tr>
      <tr><td style="padding:10px 0;border-bottom:1px solid #F3F4F6;">
        <p style="margin:0;font-size:11px;font-weight:700;color:#9CA3AF;text-transform:uppercase;letter-spacing:0.08em;">📧 Email</p>
        <p style="margin:4px 0 0;font-size:14px;"><a href="mailto:${email}" style="color:#FF7A00;text-decoration:none;">${email}</a></p>
      </td></tr>
      <tr><td style="padding:10px 0;border-bottom:1px solid #F3F4F6;">
        <p style="margin:0;font-size:11px;font-weight:700;color:#9CA3AF;text-transform:uppercase;letter-spacing:0.08em;">📞 Phone</p>
        <p style="margin:4px 0 0;font-size:14px;color:#111827;">${phone || '<span style="color:#9CA3AF;">Not provided</span>'}</p>
      </td></tr>
      <tr><td style="padding:10px 0;border-bottom:1px solid #F3F4F6;">
        <p style="margin:0;font-size:11px;font-weight:700;color:#9CA3AF;text-transform:uppercase;letter-spacing:0.08em;">💼 Position Applied For</p>
        <p style="margin:4px 0 0;font-size:14px;color:#111827;font-weight:600;">${position}</p>
      </td></tr>
      <tr><td style="padding:10px 0;border-bottom:1px solid #F3F4F6;">
        <p style="margin:0;font-size:11px;font-weight:700;color:#9CA3AF;text-transform:uppercase;letter-spacing:0.08em;">📎 Resume</p>
        <p style="margin:4px 0 0;font-size:14px;color:#111827;">
          ${resumeFile
            ? `<span style="color:#00A651;font-weight:600;">✅ Attached — ${resumeFile.originalname}</span>`
            : '<span style="color:#9CA3AF;">Not provided</span>'}
        </p>
      </td></tr>
      <tr><td style="padding:10px 0;">
        <p style="margin:0;font-size:11px;font-weight:700;color:#9CA3AF;text-transform:uppercase;letter-spacing:0.08em;">🕐 Submitted</p>
        <p style="margin:4px 0 0;font-size:14px;color:#111827;">${getTimestamp()}</p>
      </td></tr>
    </table>

    <!-- COVER LETTER -->
    <div style="margin-top:24px;">
      <p style="margin:0 0 10px;font-size:11px;font-weight:700;color:#9CA3AF;text-transform:uppercase;letter-spacing:0.08em;">📝 Cover Letter / Message</p>
      <div style="background:#F9FAFB;border:1px solid #E5E7EB;border-radius:10px;padding:16px;">
        <p style="margin:0;font-size:14px;color:#374151;line-height:1.75;white-space:pre-wrap;">${message}</p>
      </div>
    </div>

    <!-- REPLY CTA -->
    <div style="margin-top:28px;text-align:center;">
      <a href="mailto:${email}?subject=Re: Your Application for ${encodeURIComponent(position)} at Bloomvera"
        style="display:inline-block;padding:13px 32px;${GRAD};color:#fff;font-size:14px;font-weight:700;text-decoration:none;border-radius:12px;">
        Reply to ${fullName}
      </a>
    </div>
  </td></tr>

  <!-- FOOTER -->
  <tr><td style="${FOOTER}">
    <p style="margin:0;font-size:11px;color:#9CA3AF;text-align:center;line-height:1.6;">
      Auto-generated by Bloomvera Autism career form<br/>
      © ${getYear()} Bloomvera Autism · info@bloomveraautism.com
    </p>
  </td></tr>

</table>
</td></tr></table>
</body></html>`;

  const result = await resend.emails.send({
    from: getFrom(), to: ADMIN, reply_to: email,
    subject: `💼 New Application: ${position} — ${fullName}`,
    html,
    attachments,
  });
  if (result.error) throw new Error(result.error.message);
  return result;
}

// ─────────────────────────────────────────────────────────────────
// 4. CAREER — APPLICANT CONFIRMATION
// ─────────────────────────────────────────────────────────────────
async function sendCareerConfirmationEmail({ fullName, email, position }) {
  const resend  = getResend();
  const siteUrl = process.env.FRONTEND_URL || "https://bloomveraautism.com";

  const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>Application Received — Bloomvera Autism</title></head>
<body style="margin:0;padding:0;background:#F9FAFB;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#F9FAFB;padding:40px 16px;">
<tr><td align="center">
<table width="100%" cellpadding="0" cellspacing="0" style="max-width:580px;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.07);">

  <!-- HEADER -->
  <tr><td style="${GRAD};padding:36px 32px;text-align:center;">
    <p style="margin:0 0 6px;font-size:36px;">🎉</p>
    <h1 style="margin:0;font-size:24px;font-weight:700;color:#fff;">Application Received!</h1>
    <p style="margin:8px 0 0;font-size:14px;color:rgba(255,255,255,0.85);">Thank you for applying to Bloomvera Autism</p>
  </td></tr>

  <!-- BODY -->
  <tr><td style="padding:36px 32px;">
    <p style="margin:0 0 16px;font-size:15px;color:#111827;font-weight:600;">Hi ${fullName},</p>
    <p style="margin:0 0 16px;font-size:14px;color:#6B7280;line-height:1.75;">
      Thank you for applying for the <strong style="color:#FF7A00;">${position}</strong> position at Bloomvera Autism. We've received your application and our hiring team will review it carefully.
    </p>

    <!-- POSITION BADGE -->
    <div style="background:#FFF5EB;border-radius:12px;padding:16px 20px;margin-bottom:24px;display:flex;align-items:center;">
      <p style="margin:0;font-size:13px;color:#CC6200;">
        <strong>Position Applied:</strong> ${position}
      </p>
    </div>

    <!-- WHAT HAPPENS NEXT -->
    <div style="background:#F0FDF4;border-radius:12px;padding:20px 24px;margin-bottom:28px;">
      <p style="margin:0 0 16px;font-size:12px;font-weight:700;color:#166534;text-transform:uppercase;letter-spacing:0.08em;">What Happens Next</p>
      ${[
        ["#FF7A00","1","Application Review","Our hiring team reviews your application & resume"],
        ["#FF7A00","2","Initial Screening","We'll reach out for a brief phone conversation"],
        ["#00A651","3","Interview","Meet our clinical team and learn about the role"],
        ["#00A651","4","Offer","We extend an offer to the best-fit candidate"],
      ].map(([color, num, title, sub]) => `
      <table cellpadding="0" cellspacing="0" style="margin-bottom:14px;width:100%;"><tr>
        <td style="vertical-align:top;padding-right:12px;width:32px;">
          <div style="width:24px;height:24px;background:${color};border-radius:50%;text-align:center;line-height:24px;">
            <span style="font-size:11px;font-weight:700;color:#fff;">${num}</span>
          </div>
        </td>
        <td>
          <p style="margin:0;font-size:13px;font-weight:600;color:#111827;">${title}</p>
          <p style="margin:2px 0 0;font-size:12px;color:#9CA3AF;">${sub}</p>
        </td>
      </tr></table>`).join("")}
    </div>

    <p style="margin:0 0 24px;font-size:14px;color:#6B7280;line-height:1.75;">
      We typically respond within <strong style="color:#111827;">3–5 business days</strong>. If you have any questions in the meantime, feel free to reach out.
    </p>

    <!-- CTA -->
    <div style="text-align:center;margin-bottom:28px;">
      <a href="${siteUrl}/career"
        style="display:inline-block;padding:13px 32px;${GRAD};color:#fff;font-size:14px;font-weight:700;text-decoration:none;border-radius:12px;">
        View Open Positions
      </a>
    </div>

    <!-- CONTACT -->
    <div style="border-top:1px solid #F3F4F6;padding-top:20px;text-align:center;">
      <p style="margin:0 0 4px;font-size:12px;color:#9CA3AF;">Have questions? Contact us:</p>
      <a href="mailto:info@bloomveraautism.com" style="font-size:14px;font-weight:600;color:#FF7A00;text-decoration:none;">info@bloomveraautism.com</a>
      <br/>
      <a href="tel:+17744642639" style="font-size:14px;font-weight:600;color:#FF7A00;text-decoration:none;">+1 774-464-2639</a>
    </div>
  </td></tr>

  <!-- FOOTER -->
  <tr><td style="${FOOTER}">
    <p style="margin:0;font-size:11px;color:#9CA3AF;text-align:center;line-height:1.7;">
      <strong style="color:#374151;">Bloomvera Autism</strong><br/>
      info@bloomveraautism.com &nbsp;·&nbsp; +1 774-464-2639<br/>
      2823 Marietta St, Steilacoom, WA 98388<br/><br/>
      © ${getYear()} Bloomvera Autism. All rights reserved.
    </p>
  </td></tr>

</table>
</td></tr></table>
</body></html>`;

  const result = await resend.emails.send({
    from: getFrom(), to: email,
    subject: `✅ Application Received — ${position} | Bloomvera Autism`,
    html,
  });
  if (result.error) throw new Error(result.error.message);
  return result;
}

module.exports = {
  sendAdminEmail,
  sendUserConfirmationEmail,
  sendCareerAdminEmail,
  sendCareerConfirmationEmail,
};